'use strict';
require("./Attentions.js");
require("./login.js");
require("./online.js");
require("./register.js");
require("./shop.js");
require('./AttentionBoard.js');
require('./favorite.js');
require('./FindPassword.js');
require('./VerifyCodeService.js');
